### ISSUE TITLE
Programming for QXlsx

### ISSUE THREAD

**Issue by GitterRalf** [j2doll/discussion#4]
Hi Jay Two,

is there a special sequence for troubleshooting issues, or can i choose one?
I don't want to fix the same bug you're working on right now.

Best regards Ralf

**Comment by j2doll** [comment]
Dear @GitterRalf 

The problem identified is currently being registered for the issue.  

However, because this project is an open source project, there is no fixed schedule for issues.  

Most others, including myself, are working on commercial projects, so it's hard to care about this project alone.
